name: Security Tests

on:
  pull_request:
    branches:
      - "*"

permissions:
  checks: write
  contents: read
  id-token: write

jobs:
  security-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'
          cache-dependency-path: 'frontend/pnpm-lock.yaml'

      - name: Install frontend dependencies
        run: |
          cd frontend
          pnpm install

      - name: Build frontend
        run: pnpm run build

      - name: Start application
        run: |
          docker run -d -p 80:80 --name filebrowser filebrowser

      - name: Wait for application to be ready
        run: |
          for i in {1..30}; do
            nc -zv 127.0.0.1 80 && echo "Application is ready" && exit 0
            sleep 2
          done
          echo "Application did not start in time" && exit 1

      - name: Set up BrightSec credentials
        uses: ./.github/workflows/composite/configure-bright-credentials
        with:
          BRIGHT_HOSTNAME: development.playground.brightsec.com
          BRIGHT_PROJECT_ID: 5VY4XBicodsJNKJtoPAmyP
          BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}

      - name: Install SecTesterJS dependencies
        run: |
          cd frontend/.brightsec
          pnpm i --save=false @sectester/core @sectester/repeater @sectester/scan @sectester/runner

      - name: Run security tests
        env:
          BRIGHT_HOSTNAME: development.playground.brightsec.com
          BRIGHT_PROJECT_ID: 5VY4XBicodsJNKJtoPAmyP
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}
          BRIGHT_TARGET_URL: http://127.0.0.1:80
        run: |
          node --experimental-transform-types --experimental-strip-types --experimental-detect-module \
          --disable-warning=MODULE_TYPELESS_PACKAGE_JSON --disable-warning=ExperimentalWarning \
          --test-force-exit --test "frontend/tests-examples/.brightsec/tests/*.test.ts" --test-concurrency=4

      - name: Stop application
        run: docker stop filebrowser && docker rm filebrowser
